
from __future__ import annotations

import json
import os
from langchain_openai import ChatOpenAI

from .config import DEFAULT_MODEL, DEFAULT_MAX_TEXT_CHARS, OPENROUTER_BASE_URL
from .models import EvaluationResponse


def build_prompt(supplier_name: str, proposal_text: str, criteria: list[dict]) -> str:
    criteria_json = json.dumps(criteria, indent=2)
    return f"""
You are evaluating ONE supplier proposal for an RFP.

RULES:
1. Use only evidence present in the supplied proposal text.
2. Return exactly one result for every active criterion.
3. Each score must be numeric and between 0 and the configured max_score.
4. Put short proposal evidence in the evidence field.
5. If evidence is missing, score conservatively and state that it is missing.
6. Do NOT calculate weighted totals, peer benchmarks, PPI, tie-breaks, or rank.
7. Do NOT infer facts absent from the proposal.

ACTIVE CRITERIA:
{criteria_json}

SUPPLIER:
{supplier_name}

SUPPLIER PROPOSAL:
{proposal_text[:DEFAULT_MAX_TEXT_CHARS]}
""".strip()


def evaluate_with_llm(
    supplier_name: str,
    proposal_text: str,
    criteria: list[dict],
    model: str = DEFAULT_MODEL,
    api_key: str | None = None,
    base_url: str | None = None,
) -> dict:
    openrouter_key = api_key or os.getenv("OPENROUTER_API_KEY")
    if not openrouter_key:
        raise ValueError(
            "OpenRouter API key is missing. Set OPENROUTER_API_KEY "
            "or enter the key in the Streamlit sidebar."
        )

    selected_model = model or os.getenv("OPENROUTER_MODEL") or DEFAULT_MODEL

    default_headers = {}
    referer = os.getenv("OPENROUTER_HTTP_REFERER")
    app_name = os.getenv("OPENROUTER_APP_NAME")
    if referer:
        default_headers["HTTP-Referer"] = referer
    if app_name:
        default_headers["X-Title"] = app_name

    llm = ChatOpenAI(
        model=selected_model,
        temperature=0,
        api_key=openrouter_key,
        base_url=base_url or OPENROUTER_BASE_URL,
        default_headers=default_headers or None,
    )

    structured_llm = llm.with_structured_output(EvaluationResponse)
    result = structured_llm.invoke(
        build_prompt(
            supplier_name=supplier_name,
            proposal_text=proposal_text,
            criteria=criteria,
        )
    )
    return result.model_dump()


def evaluate_mock(supplier_name: str, proposal_text: str, criteria: list[dict]) -> dict:
    text = proposal_text.lower()
    keyword_sets = {
        1: ["architecture", "integration", "scalability", "api", "technical"],
        2: ["timeline", "milestone", "staffing", "implementation", "risk"],
        3: ["price", "pricing", "cost", "assumption", "commercial"],
        4: ["security", "iso 27001", "soc 2", "privacy", "audit", "encryption"],
        5: ["support", "reference", "experience", "sla", "project"],
    }

    criteria_out = []
    for criterion in criteria:
        criterion_id = int(criterion["criterion_id"])
        max_score = float(criterion["max_score"])
        hits = sum(
            1 for keyword in keyword_sets.get(criterion_id, [])
            if keyword in text
        )
        score = min(max_score, 4 + hits * 1.2)
        criteria_out.append({
            "criterion_id": criterion_id,
            "score": round(score, 1),
            "max_score": max_score,
            "justification": f"Demo-mode score based on {hits} matched evidence indicators.",
            "evidence": (
                "Offline demo mode is keyword-based; use OpenRouter LLM mode "
                "for semantic evidence-grounded evaluation."
            ),
        })

    return {
        "supplier_name": supplier_name,
        "criteria": criteria_out,
        "risks": ["Demo mode is deterministic and not a semantic LLM assessment."],
        "overall_summary": "Generated by the offline demo evaluator.",
    }
